### ISSUE TITLE
No code displayed with a newKaku device

### ISSUE THREAD

**Issue by hugodu21** [1technophile/NewRemoteSwitch#4]
I used the ShowReceivedCode.ino with an ESP8266 NodeMCU.

When i press on/off on the device Dio(chacon) nothing is displayed on the serial.

No problem on Arnuio with the official NewRemoteSwitch.

**Comment by 1technophile** [comment]
> No problem on Arnuio with the official NewRemoteSwitch

Could you point me where it comes from?

**Comment by hugodu21** [comment]
oh its stange it does not work 100% just 1%.

im checking everything to be sure its not a false contact, 
the receptor is working fine on the ESP8266 with RCSwitch (with a simple rcswitch emetor). 100%

the emetor is working fine with rflink on arduino mega 100%

with your ShowReceivedCode.ino on ESP8266 i could get the displayed code just 3 times ! i dont know why .... i flash back to rcswitch, no problem, without touching any wire i flash back to ShowReceivedCode... no reception.

its a weird issue :(

**Comment by hugodu21** [comment]
oh god! sorry. its the receptor... reception issue...
 your code is working 100%.

sorry for disturbing you.

thanks you so much for your work, it open me a lot of possibility in my projects !

**Comment by 1technophile** [comment]
Ok, good to hear that it works. Could you close the issue  ?

**Comment by hugodu21** [comment]
it was a receptor issue...
