### ISSUE TITLE
Cant compil Retransmitter.ino when i select a ESP8266 mudule in arduino IDE

### ISSUE THREAD

**Issue by hugodu21** [1technophile/NewRemoteSwitch#5]
Hello,

does the Retransmitter.ino should work with ESP8266 NodeMcu module ?
I got the following error

This line is highlighted

void setup() {
  // See example ShowReceivedCode for info on this
  **NewRemoteReceiver::init(0, 2, retransmitter);**
}

![error message](https://user-images.githubusercontent.com/58641185/71130229-b3775a80-21f1-11ea-8dea-b4e81fa8e749.JPG)

```
\Arduino\libraries\NewRemoteSwitch-master/NewRemoteReceiver.h:73:15: note: static void NewRemoteReceiver::init(int8_t, byte, NewRemoteReceiverCallBack)

   static void init(int8_t interrupt, byte minRepeats, NewRemoteReceiverCallBack callback);

               ^
```
Thanks for your support !
The ShowReceivedCode works perfectly !

Now i want to reproduce the code received to retransmit it on demand :)

Thanks again

**Comment by hugodu21** [comment]
I'm trying to understand the code, but I'm not a developer.

Since I get the code issued. (Using ShowReceivedcode.ino)

Wouldn't it be enough for me to pass it as an argument in a transmition function?

Thanks !

**Comment by hugodu21** [comment]
Is it possible to display the code on the Serial, 

so i could write it in my code to transmit it ?

**Comment by hugodu21** [comment]
oh maybe LearnCode.ino could suits me better !
Im gona try this tonight !

**Comment by 1technophile** [comment]
> Hello,
does the Retransmitter.ino should work with ESP8266 NodeMcu module ?
I got the following error

Hello, In the orange log of your arduino IDE you can see that the IDE find several libraries for newremoteswitch
Are you sure it takes the good one?

**Comment by hugodu21** [comment]
hello,

yes, i removed it to be sure but its the same issue.

with esp8266 selected:
![retransmitter_esp8266](https://user-images.githubusercontent.com/58641185/71213160-28f72f80-22b3-11ea-8b52-a99062c1e17f.JPG)

with arduino  selected:
![retransmitter_arduino](https://user-images.githubusercontent.com/58641185/71213120-1846b980-22b3-11ea-9097-450a5d590b56.JPG)

I found a solution with another code, so if you dont have time, dont worry about me!

Thank you for your response.

**Comment by hugodu21** [comment]
in fact your program is better, i cant have the good code with the other code in found.

Is there a way to get the receivedCode un your showCode function easyly ?

**Comment by 1technophile** [comment]
> Is there a way to get the receivedCode un your showCode function easyly ?

Do you succeed in compiling ShowReceivedCode.ino

**Comment by hugodu21** [comment]
yes, i think its ok for the receive code,

i use the showcode function to get the code and update the status of the lights in jeedom using a http get.

i used:

```
void showCode(unsigned int period, unsigned long address, unsigned long groupBit, unsigned long unit, unsigned long switchType) {
      BoutonID = address;
      BoutonID *= 2;
      if (groupBit) BoutonID += 1;
      BoutonID *= 2;
      if (switchType) BoutonID += 1;
      BoutonID *= 16;
      BoutonID += unit;
...

and i use another library to send this code with the 433mhz transmiter

**Comment by 1technophile** [comment]
If you want to integrate with jeedom you could use [OpenMQTTGateway](https://docs.openmqttgateway.com) directly. and interface through MQTT.

The gateway corresponding to NewRemoteSwitch library is ZgatewayRF2

**Comment by hugodu21** [comment]
thanks i will try it :)

I already tryed rflink with Jeedom plugin, but im starting to enjoy the electronic and i would like to include my own little noobs beginer code inside the esp8266 (or arduino)

in parallel i began the openclassroom tutorials for C learning

is it possible to include easy my own code inside the MQTT gateway ?

**Comment by 1technophile** [comment]
> is it possible to include easy my own code inside the MQTT gateway ?

Yes you can see there
https://docs.openmqttgateway.com/participate/development.html
