### ISSUE TITLE
NodeMCU ESP-12E Compatibility

### ISSUE THREAD

**Issue by Jan1902** [1technophile/NewRemoteSwitch#6]
First off, I have to say I am quite new to working with arduino stuff.

I've recently tried using the RC-Switch Library to control my self learning remote switches and failed, so after a bit of searching I got here and tried this library on the Arduino and it worked wonderfully. Unfornunately when I tried to use it on the ESP-8266 board I had laying around, the serial monitor just gets flooded with an error saying "ISR not in IRAM!".
Unfortunately I haven't found too much info on how to fix this.

The exact message is the following:

```
>>>stack>>>

ctx: cont
sp: 3ffffee0 end: 3fffffc0 offset: 0000
3ffffee0:  00000c68 feefeffe feefeffe feefeffe  
3ffffef0:  000000fe 00000000 00000000 00000000  
3fffff00:  00000000 00000000 00000000 00ff0000  
3fffff10:  5ffffe00 5ffffe00 feefeffe 00000000  
3fffff20:  00000003 00000000 3ffee374 4020225a  
3fffff30:  40100402 0001c200 00000000 40202270  
3fffff40:  00000003 40203235 3ffee374 40202781  
3fffff50:  00000000 00000001 3ffee394 3ffee3fc  
3fffff60:  00000000 00000001 3ffee394 3ffee3fc  
3fffff70:  3fffdad0 00000000 3ffee374 40202830  
3fffff80:  0001c200 0000001c 00000000 40201560  
3fffff90:  3fffdad0 00000000 3ffee3bc 40201116  
3fffffa0:  feefeffe feefeffe feefeffe 40201eb0  
3fffffb0:  feefeffe feefeffe 3ffe84e4 40100d0d  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
ISR not in IRAM!

User exception (panic/abort/assert)
Abort called
```

In case this is a known issue, that I just happenened to not find until now, please let me know.
Otherwhise I hope someone can help me with this probably simple problem :)

**Comment by 1technophile** [comment]
May you precise which arduino-esp8266 you are using and try to update maybe

**Comment by Jan1902** [comment]
I am using the NodeMCU ESP-12E (by AZ-Delivery) according to the packaging, the chip itself says ESP8266MOD 12-F.
And what exactly should I update ? Should be using the latest versions of both Arduino and the library I think.

**Comment by 1technophile** [comment]
From the arduino board manager try to update the version of Arduino-esp8266 framework

**Comment by Jan1902** [comment]
Unfortunately also updating the ESP-8266-framework had no effect. But after some more research I found this might be an Issue with the ESP's software itself. I ended up working around this problem, by using an Arduino Uno, on which this library is working perfectly, to receive the signals, and then purely sending them on the ESPs, which works like a charm.
